package com.Production.Dto;

public class PRODUCTION_INFO_TBL_1 {

	// 순번
	String PRODUCTION_INFO_NUM;
	// 품목 시리얼 번호
	String PRODUCTION_SERIAL_NUM;
	// 품목 코드
	String PRODUCTION_PRODUCT_CODE;
	// 품목 명
	String PRODUCT_ITEM_NAME;
	// 생산 수량
	String PRODUCTION_VOLUME;
	// 생산 수량 합
	String PRODUCTION_VOLUME_SUM;
	// 불량 수량
	String PRODUCTION_DEFECT_CODE;
	// 불량 수량 이름
	String PRODUCTION_DEFECT_NAME;
	// 불량 수량 합
	String PRODUCTION_DEFECT_CODE_SUM;
	// 양품 수량 
	String QUANTITY_GOODS;
	// 불량률
	String DEFECT_RATE;
	// 설비코드
	String PRODUCTION_EQUIPMENT_CODE;
	// 설비명
	String EQUIPMENT_INFO_NAME;
	// 금형no
	String PRODUCTION_MOLD_INFO_CODE;
	// 금형명
	String MOLD_INFO_NAME;
	// 시간
	String PRODUCTION_MODIFY_D;
	// 사용자 코드
	String USER_CODE;
	// 사용자 이름
	String USER_NAME;
	// 시간
	String TIME;
	
	public PRODUCTION_INFO_TBL_1() {
		super();
	}
	
	@Override
	public String toString() {
		return "PRODUCTION_INFO_TBL_1 [PRODUCTION_INFO_NUM=" + PRODUCTION_INFO_NUM + ", PRODUCTION_SERIAL_NUM="
				+ PRODUCTION_SERIAL_NUM + ", PRODUCTION_PRODUCT_CODE=" + PRODUCTION_PRODUCT_CODE
				+ ", PRODUCT_ITEM_NAME=" + PRODUCT_ITEM_NAME + ", PRODUCTION_VOLUME=" + PRODUCTION_VOLUME
				+ ", PRODUCTION_VOLUME_SUM=" + PRODUCTION_VOLUME_SUM + ", PRODUCTION_DEFECT_CODE="
				+ PRODUCTION_DEFECT_CODE + ", PRODUCTION_DEFECT_NAME=" + PRODUCTION_DEFECT_NAME
				+ ", PRODUCTION_DEFECT_CODE_SUM=" + PRODUCTION_DEFECT_CODE_SUM + ", QUANTITY_GOODS=" + QUANTITY_GOODS
				+ ", DEFECT_RATE=" + DEFECT_RATE + ", PRODUCTION_EQUIPMENT_CODE=" + PRODUCTION_EQUIPMENT_CODE
				+ ", EQUIPMENT_INFO_NAME=" + EQUIPMENT_INFO_NAME + ", PRODUCTION_MOLD_INFO_CODE="
				+ PRODUCTION_MOLD_INFO_CODE + ", MOLD_INFO_NAME=" + MOLD_INFO_NAME + ", PRODUCTION_MODIFY_D="
				+ PRODUCTION_MODIFY_D + ", USER_CODE=" + USER_CODE + ", USER_NAME=" + USER_NAME + ", TIME=" + TIME
				+ "]";
	}

	public String getPRODUCTION_SERIAL_NUM() {
		return PRODUCTION_SERIAL_NUM;
	}

	public void setPRODUCTION_SERIAL_NUM(String pRODUCTION_SERIAL_NUM) {
		PRODUCTION_SERIAL_NUM = pRODUCTION_SERIAL_NUM;
	}

	public String getPRODUCTION_PRODUCT_CODE() {
		return PRODUCTION_PRODUCT_CODE;
	}

	public void setPRODUCTION_PRODUCT_CODE(String pRODUCTION_PRODUCT_CODE) {
		PRODUCTION_PRODUCT_CODE = pRODUCTION_PRODUCT_CODE;
	}

	public String getPRODUCT_ITEM_NAME() {
		return PRODUCT_ITEM_NAME;
	}

	public void setPRODUCT_ITEM_NAME(String pRODUCT_ITEM_NAME) {
		PRODUCT_ITEM_NAME = pRODUCT_ITEM_NAME;
	}

	public String getPRODUCTION_VOLUME() {
		return PRODUCTION_VOLUME;
	}

	public void setPRODUCTION_VOLUME(String pRODUCTION_VOLUME) {
		PRODUCTION_VOLUME = pRODUCTION_VOLUME;
	}

	public String getPRODUCTION_VOLUME_SUM() {
		return PRODUCTION_VOLUME_SUM;
	}

	public void setPRODUCTION_VOLUME_SUM(String pRODUCTION_VOLUME_SUM) {
		PRODUCTION_VOLUME_SUM = pRODUCTION_VOLUME_SUM;
	}

	public String getPRODUCTION_DEFECT_CODE() {
		return PRODUCTION_DEFECT_CODE;
	}

	public void setPRODUCTION_DEFECT_CODE(String pRODUCTION_DEFECT_CODE) {
		PRODUCTION_DEFECT_CODE = pRODUCTION_DEFECT_CODE;
	}

	public String getPRODUCTION_DEFECT_CODE_SUM() {
		return PRODUCTION_DEFECT_CODE_SUM;
	}

	public void setPRODUCTION_DEFECT_CODE_SUM(String pRODUCTION_DEFECT_CODE_SUM) {
		PRODUCTION_DEFECT_CODE_SUM = pRODUCTION_DEFECT_CODE_SUM;
	}

	public String getQUANTITY_GOODS() {
		return QUANTITY_GOODS;
	}

	public void setQUANTITY_GOODS(String qUANTITY_GOODS) {
		QUANTITY_GOODS = qUANTITY_GOODS;
	}

	public String getDEFECT_RATE() {
		return DEFECT_RATE;
	}

	public void setDEFECT_RATE(String dEFECT_RATE) {
		DEFECT_RATE = dEFECT_RATE;
	}

	public String getPRODUCTION_EQUIPMENT_CODE() {
		return PRODUCTION_EQUIPMENT_CODE;
	}

	public void setPRODUCTION_EQUIPMENT_CODE(String pRODUCTION_EQUIPMENT_CODE) {
		PRODUCTION_EQUIPMENT_CODE = pRODUCTION_EQUIPMENT_CODE;
	}

	public String getEQUIPMENT_INFO_NAME() {
		return EQUIPMENT_INFO_NAME;
	}

	public void setEQUIPMENT_INFO_NAME(String eQUIPMENT_INFO_NAME) {
		EQUIPMENT_INFO_NAME = eQUIPMENT_INFO_NAME;
	}

	public String getPRODUCTION_MOLD_INFO_CODE() {
		return PRODUCTION_MOLD_INFO_CODE;
	}

	public void setPRODUCTION_MOLD_INFO_CODE(String pRODUCTION_MOLD_INFO_CODE) {
		PRODUCTION_MOLD_INFO_CODE = pRODUCTION_MOLD_INFO_CODE;
	}

	public String getMOLD_INFO_NAME() {
		return MOLD_INFO_NAME;
	}

	public void setMOLD_INFO_NAME(String mOLD_INFO_NAME) {
		MOLD_INFO_NAME = mOLD_INFO_NAME;
	}

	public String getPRODUCTION_MODIFY_D() {
		return PRODUCTION_MODIFY_D;
	}

	public void setPRODUCTION_MODIFY_D(String pRODUCTION_MODIFY_D) {
		PRODUCTION_MODIFY_D = pRODUCTION_MODIFY_D;
	}

	public String getPRODUCTION_INFO_NUM() {
		return PRODUCTION_INFO_NUM;
	}

	public void setPRODUCTION_INFO_NUM(String pRODUCTION_INFO_NUM) {
		PRODUCTION_INFO_NUM = pRODUCTION_INFO_NUM;
	}

	public String getUSER_CODE() {
		return USER_CODE;
	}

	public void setUSER_CODE(String uSER_CODE) {
		USER_CODE = uSER_CODE;
	}

	public String getUSER_NAME() {
		return USER_NAME;
	}

	public void setUSER_NAME(String uSER_NAME) {
		USER_NAME = uSER_NAME;
	}

	public String getTIME() {
		return TIME;
	}

	public void setTIME(String tIME) {
		TIME = tIME;
	}

	public String getPRODUCTION_DEFECT_NAME() {
		return PRODUCTION_DEFECT_NAME;
	}

	public void setPRODUCTION_DEFECT_NAME(String pRODUCTION_DEFECT_NAME) {
		PRODUCTION_DEFECT_NAME = pRODUCTION_DEFECT_NAME;
	}
	
}
