package com.Production.Dto;

public class PRODUCTION_INFO_YEAR {

	private int Id;
	private int PRODUCTION_P_Qty;
	private int PRODUCTION_P_Qty_1; // 1월 생산수량
	private int PRODUCTION_P_Qty_2; // 2월 생산수량
	private int PRODUCTION_P_Qty_3; // 3월 생산수량
	private int PRODUCTION_P_Qty_4; // 4월 생산수량
	private int PRODUCTION_P_Qty_5; // 5월 생산수량
	private int PRODUCTION_P_Qty_6; // 6월 생산수량
	private int PRODUCTION_P_Qty_7; // 7월 생산수량
	private int PRODUCTION_P_Qty_8; // 8월 생산수량
	private int PRODUCTION_P_Qty_9; // 9월 생산수량
	private int PRODUCTION_P_Qty_10; // 10월 생산수량
	private int PRODUCTION_P_Qty_11; // 11월 생산수량
	private int PRODUCTION_P_Qty_12; // 12월 생산수량
	private int PRODUCTION_B_Qty_1; // 1월 불량수량
	private int PRODUCTION_B_Qty_2; // 2월 불량수량
	private int PRODUCTION_B_Qty_3; // 3월 불량수량
	private int PRODUCTION_B_Qty_4; // 4월 불량수량
	private int PRODUCTION_B_Qty_5; // 5월 불량수량
	private int PRODUCTION_B_Qty_6; // 6월 불량수량
	private int PRODUCTION_B_Qty_7; // 7월 불량수량
	private int PRODUCTION_B_Qty_8; // 8월 불량수량
	private int PRODUCTION_B_Qty_9; // 9월 불량수량
	private int PRODUCTION_B_Qty_10; // 10월 불량수량
	private int PRODUCTION_B_Qty_11; // 11월 불량수량
	private int PRODUCTION_B_Qty_12; // 12월 불량수량
	private int PRODUCTION_PRODUCTS_VOLUME_1; // 1월 양품수량
	private int PRODUCTION_PRODUCTS_VOLUME_2; // 2월 양품수량
	private int PRODUCTION_PRODUCTS_VOLUME_3; // 3월 양품수량
	private int PRODUCTION_PRODUCTS_VOLUME_4; // 4월 양품수량
	private int PRODUCTION_PRODUCTS_VOLUME_5; // 5월 양품수량
	private int PRODUCTION_PRODUCTS_VOLUME_6; // 6월 양품수량
	private int PRODUCTION_PRODUCTS_VOLUME_7; // 7월 양품수량
	private int PRODUCTION_PRODUCTS_VOLUME_8; // 8월 양품수량
	private int PRODUCTION_PRODUCTS_VOLUME_9; // 9월 양품수량
	private int PRODUCTION_PRODUCTS_VOLUME_10; // 10월 양품수량
	private int PRODUCTION_PRODUCTS_VOLUME_11; // 11월 양품수량
	private int PRODUCTION_PRODUCTS_VOLUME_12; // 12월 양품수량
	private String PRODUCTION_DEFECT_RATE_1; // 1월 불량율
	private String PRODUCTION_DEFECT_RATE_2; // 2월 불량율
	private String PRODUCTION_DEFECT_RATE_3; // 3월 불량율
	private String PRODUCTION_DEFECT_RATE_4; // 4월 불량율
	private String PRODUCTION_DEFECT_RATE_5; // 5월 불량율
	private String PRODUCTION_DEFECT_RATE_6; // 6월 불량율
	private String PRODUCTION_DEFECT_RATE_7; // 7월 불량율
	private String PRODUCTION_DEFECT_RATE_8; // 8월 불량율
	private String PRODUCTION_DEFECT_RATE_9; // 9월 불량율
	private String PRODUCTION_DEFECT_RATE_10; // 10월 불량율
	private String PRODUCTION_DEFECT_RATE_11; // 11월 불량율
	private String PRODUCTION_DEFECT_RATE_12; // 12월 불량율
	private String PRODUCTION_PRODUCT_CODE; // 제품No
	private String PRODUCT_ITEM_NAME; // 제품명
	private String PRODUCTION_MODIFY_D; // 날짜
	private String M; // 월
	private int SUM_PRODUCTION_P_Qty; // 생삽합계
	private int SUM_PRODUCTION_B_Qty; // 불량합계
	private int SUM_PRODUCTION_PRODUCTS_VOLUME; // 양품수량합계
	private String SUM_PRODUCTION_PRODUCTION_DEFECT_RATE; // 불량율합계
	
	public int getId() {
		return Id;
	}
	public void setId(int id) {
		Id = id;
	}
	public int getPRODUCTION_P_Qty() {
		return PRODUCTION_P_Qty;
	}
	public void setPRODUCTION_P_Qty(int pRODUCTION_P_Qty) {
		PRODUCTION_P_Qty = pRODUCTION_P_Qty;
	}
	public int getPRODUCTION_P_Qty_1() {
		return PRODUCTION_P_Qty_1;
	}
	public void setPRODUCTION_P_Qty_1(int pRODUCTION_P_Qty_1) {
		PRODUCTION_P_Qty_1 = pRODUCTION_P_Qty_1;
	}
	public int getPRODUCTION_P_Qty_2() {
		return PRODUCTION_P_Qty_2;
	}
	public void setPRODUCTION_P_Qty_2(int pRODUCTION_P_Qty_2) {
		PRODUCTION_P_Qty_2 = pRODUCTION_P_Qty_2;
	}
	public int getPRODUCTION_P_Qty_3() {
		return PRODUCTION_P_Qty_3;
	}
	public void setPRODUCTION_P_Qty_3(int pRODUCTION_P_Qty_3) {
		PRODUCTION_P_Qty_3 = pRODUCTION_P_Qty_3;
	}
	public int getPRODUCTION_P_Qty_4() {
		return PRODUCTION_P_Qty_4;
	}
	public void setPRODUCTION_P_Qty_4(int pRODUCTION_P_Qty_4) {
		PRODUCTION_P_Qty_4 = pRODUCTION_P_Qty_4;
	}
	public int getPRODUCTION_P_Qty_5() {
		return PRODUCTION_P_Qty_5;
	}
	public void setPRODUCTION_P_Qty_5(int pRODUCTION_P_Qty_5) {
		PRODUCTION_P_Qty_5 = pRODUCTION_P_Qty_5;
	}
	public int getPRODUCTION_P_Qty_6() {
		return PRODUCTION_P_Qty_6;
	}
	public void setPRODUCTION_P_Qty_6(int pRODUCTION_P_Qty_6) {
		PRODUCTION_P_Qty_6 = pRODUCTION_P_Qty_6;
	}
	public int getPRODUCTION_P_Qty_7() {
		return PRODUCTION_P_Qty_7;
	}
	public void setPRODUCTION_P_Qty_7(int pRODUCTION_P_Qty_7) {
		PRODUCTION_P_Qty_7 = pRODUCTION_P_Qty_7;
	}
	public int getPRODUCTION_P_Qty_8() {
		return PRODUCTION_P_Qty_8;
	}
	public void setPRODUCTION_P_Qty_8(int pRODUCTION_P_Qty_8) {
		PRODUCTION_P_Qty_8 = pRODUCTION_P_Qty_8;
	}
	public int getPRODUCTION_P_Qty_9() {
		return PRODUCTION_P_Qty_9;
	}
	public void setPRODUCTION_P_Qty_9(int pRODUCTION_P_Qty_9) {
		PRODUCTION_P_Qty_9 = pRODUCTION_P_Qty_9;
	}
	public int getPRODUCTION_P_Qty_10() {
		return PRODUCTION_P_Qty_10;
	}
	public void setPRODUCTION_P_Qty_10(int pRODUCTION_P_Qty_10) {
		PRODUCTION_P_Qty_10 = pRODUCTION_P_Qty_10;
	}
	public int getPRODUCTION_P_Qty_11() {
		return PRODUCTION_P_Qty_11;
	}
	public void setPRODUCTION_P_Qty_11(int pRODUCTION_P_Qty_11) {
		PRODUCTION_P_Qty_11 = pRODUCTION_P_Qty_11;
	}
	public int getPRODUCTION_P_Qty_12() {
		return PRODUCTION_P_Qty_12;
	}
	public void setPRODUCTION_P_Qty_12(int pRODUCTION_P_Qty_12) {
		PRODUCTION_P_Qty_12 = pRODUCTION_P_Qty_12;
	}
	public int getPRODUCTION_B_Qty_1() {
		return PRODUCTION_B_Qty_1;
	}
	public void setPRODUCTION_B_Qty_1(int pRODUCTION_B_Qty_1) {
		PRODUCTION_B_Qty_1 = pRODUCTION_B_Qty_1;
	}
	public int getPRODUCTION_B_Qty_2() {
		return PRODUCTION_B_Qty_2;
	}
	public void setPRODUCTION_B_Qty_2(int pRODUCTION_B_Qty_2) {
		PRODUCTION_B_Qty_2 = pRODUCTION_B_Qty_2;
	}
	public int getPRODUCTION_B_Qty_3() {
		return PRODUCTION_B_Qty_3;
	}
	public void setPRODUCTION_B_Qty_3(int pRODUCTION_B_Qty_3) {
		PRODUCTION_B_Qty_3 = pRODUCTION_B_Qty_3;
	}
	public int getPRODUCTION_B_Qty_4() {
		return PRODUCTION_B_Qty_4;
	}
	public void setPRODUCTION_B_Qty_4(int pRODUCTION_B_Qty_4) {
		PRODUCTION_B_Qty_4 = pRODUCTION_B_Qty_4;
	}
	public int getPRODUCTION_B_Qty_5() {
		return PRODUCTION_B_Qty_5;
	}
	public void setPRODUCTION_B_Qty_5(int pRODUCTION_B_Qty_5) {
		PRODUCTION_B_Qty_5 = pRODUCTION_B_Qty_5;
	}
	public int getPRODUCTION_B_Qty_6() {
		return PRODUCTION_B_Qty_6;
	}
	public void setPRODUCTION_B_Qty_6(int pRODUCTION_B_Qty_6) {
		PRODUCTION_B_Qty_6 = pRODUCTION_B_Qty_6;
	}
	public int getPRODUCTION_B_Qty_7() {
		return PRODUCTION_B_Qty_7;
	}
	public void setPRODUCTION_B_Qty_7(int pRODUCTION_B_Qty_7) {
		PRODUCTION_B_Qty_7 = pRODUCTION_B_Qty_7;
	}
	public int getPRODUCTION_B_Qty_8() {
		return PRODUCTION_B_Qty_8;
	}
	public void setPRODUCTION_B_Qty_8(int pRODUCTION_B_Qty_8) {
		PRODUCTION_B_Qty_8 = pRODUCTION_B_Qty_8;
	}
	public int getPRODUCTION_B_Qty_9() {
		return PRODUCTION_B_Qty_9;
	}
	public void setPRODUCTION_B_Qty_9(int pRODUCTION_B_Qty_9) {
		PRODUCTION_B_Qty_9 = pRODUCTION_B_Qty_9;
	}
	public int getPRODUCTION_B_Qty_10() {
		return PRODUCTION_B_Qty_10;
	}
	public void setPRODUCTION_B_Qty_10(int pRODUCTION_B_Qty_10) {
		PRODUCTION_B_Qty_10 = pRODUCTION_B_Qty_10;
	}
	public int getPRODUCTION_B_Qty_11() {
		return PRODUCTION_B_Qty_11;
	}
	public void setPRODUCTION_B_Qty_11(int pRODUCTION_B_Qty_11) {
		PRODUCTION_B_Qty_11 = pRODUCTION_B_Qty_11;
	}
	public int getPRODUCTION_B_Qty_12() {
		return PRODUCTION_B_Qty_12;
	}
	public void setPRODUCTION_B_Qty_12(int pRODUCTION_B_Qty_12) {
		PRODUCTION_B_Qty_12 = pRODUCTION_B_Qty_12;
	}
	public int getPRODUCTION_PRODUCTS_VOLUME_1() {
		return PRODUCTION_PRODUCTS_VOLUME_1;
	}
	public void setPRODUCTION_PRODUCTS_VOLUME_1(int pRODUCTION_PRODUCTS_VOLUME_1) {
		PRODUCTION_PRODUCTS_VOLUME_1 = pRODUCTION_PRODUCTS_VOLUME_1;
	}
	public int getPRODUCTION_PRODUCTS_VOLUME_2() {
		return PRODUCTION_PRODUCTS_VOLUME_2;
	}
	public void setPRODUCTION_PRODUCTS_VOLUME_2(int pRODUCTION_PRODUCTS_VOLUME_2) {
		PRODUCTION_PRODUCTS_VOLUME_2 = pRODUCTION_PRODUCTS_VOLUME_2;
	}
	public int getPRODUCTION_PRODUCTS_VOLUME_3() {
		return PRODUCTION_PRODUCTS_VOLUME_3;
	}
	public void setPRODUCTION_PRODUCTS_VOLUME_3(int pRODUCTION_PRODUCTS_VOLUME_3) {
		PRODUCTION_PRODUCTS_VOLUME_3 = pRODUCTION_PRODUCTS_VOLUME_3;
	}
	public int getPRODUCTION_PRODUCTS_VOLUME_4() {
		return PRODUCTION_PRODUCTS_VOLUME_4;
	}
	public void setPRODUCTION_PRODUCTS_VOLUME_4(int pRODUCTION_PRODUCTS_VOLUME_4) {
		PRODUCTION_PRODUCTS_VOLUME_4 = pRODUCTION_PRODUCTS_VOLUME_4;
	}
	public int getPRODUCTION_PRODUCTS_VOLUME_5() {
		return PRODUCTION_PRODUCTS_VOLUME_5;
	}
	public void setPRODUCTION_PRODUCTS_VOLUME_5(int pRODUCTION_PRODUCTS_VOLUME_5) {
		PRODUCTION_PRODUCTS_VOLUME_5 = pRODUCTION_PRODUCTS_VOLUME_5;
	}
	public int getPRODUCTION_PRODUCTS_VOLUME_6() {
		return PRODUCTION_PRODUCTS_VOLUME_6;
	}
	public void setPRODUCTION_PRODUCTS_VOLUME_6(int pRODUCTION_PRODUCTS_VOLUME_6) {
		PRODUCTION_PRODUCTS_VOLUME_6 = pRODUCTION_PRODUCTS_VOLUME_6;
	}
	public int getPRODUCTION_PRODUCTS_VOLUME_7() {
		return PRODUCTION_PRODUCTS_VOLUME_7;
	}
	public void setPRODUCTION_PRODUCTS_VOLUME_7(int pRODUCTION_PRODUCTS_VOLUME_7) {
		PRODUCTION_PRODUCTS_VOLUME_7 = pRODUCTION_PRODUCTS_VOLUME_7;
	}
	public int getPRODUCTION_PRODUCTS_VOLUME_8() {
		return PRODUCTION_PRODUCTS_VOLUME_8;
	}
	public void setPRODUCTION_PRODUCTS_VOLUME_8(int pRODUCTION_PRODUCTS_VOLUME_8) {
		PRODUCTION_PRODUCTS_VOLUME_8 = pRODUCTION_PRODUCTS_VOLUME_8;
	}
	public int getPRODUCTION_PRODUCTS_VOLUME_9() {
		return PRODUCTION_PRODUCTS_VOLUME_9;
	}
	public void setPRODUCTION_PRODUCTS_VOLUME_9(int pRODUCTION_PRODUCTS_VOLUME_9) {
		PRODUCTION_PRODUCTS_VOLUME_9 = pRODUCTION_PRODUCTS_VOLUME_9;
	}
	public int getPRODUCTION_PRODUCTS_VOLUME_10() {
		return PRODUCTION_PRODUCTS_VOLUME_10;
	}
	public void setPRODUCTION_PRODUCTS_VOLUME_10(int pRODUCTION_PRODUCTS_VOLUME_10) {
		PRODUCTION_PRODUCTS_VOLUME_10 = pRODUCTION_PRODUCTS_VOLUME_10;
	}
	public int getPRODUCTION_PRODUCTS_VOLUME_11() {
		return PRODUCTION_PRODUCTS_VOLUME_11;
	}
	public void setPRODUCTION_PRODUCTS_VOLUME_11(int pRODUCTION_PRODUCTS_VOLUME_11) {
		PRODUCTION_PRODUCTS_VOLUME_11 = pRODUCTION_PRODUCTS_VOLUME_11;
	}
	public int getPRODUCTION_PRODUCTS_VOLUME_12() {
		return PRODUCTION_PRODUCTS_VOLUME_12;
	}
	public void setPRODUCTION_PRODUCTS_VOLUME_12(int pRODUCTION_PRODUCTS_VOLUME_12) {
		PRODUCTION_PRODUCTS_VOLUME_12 = pRODUCTION_PRODUCTS_VOLUME_12;
	}
	public String getPRODUCTION_DEFECT_RATE_1() {
		return PRODUCTION_DEFECT_RATE_1;
	}
	public void setPRODUCTION_DEFECT_RATE_1(String pRODUCTION_DEFECT_RATE_1) {
		PRODUCTION_DEFECT_RATE_1 = pRODUCTION_DEFECT_RATE_1;
	}
	public String getPRODUCTION_DEFECT_RATE_2() {
		return PRODUCTION_DEFECT_RATE_2;
	}
	public void setPRODUCTION_DEFECT_RATE_2(String pRODUCTION_DEFECT_RATE_2) {
		PRODUCTION_DEFECT_RATE_2 = pRODUCTION_DEFECT_RATE_2;
	}
	public String getPRODUCTION_DEFECT_RATE_3() {
		return PRODUCTION_DEFECT_RATE_3;
	}
	public void setPRODUCTION_DEFECT_RATE_3(String pRODUCTION_DEFECT_RATE_3) {
		PRODUCTION_DEFECT_RATE_3 = pRODUCTION_DEFECT_RATE_3;
	}
	public String getPRODUCTION_DEFECT_RATE_4() {
		return PRODUCTION_DEFECT_RATE_4;
	}
	public void setPRODUCTION_DEFECT_RATE_4(String pRODUCTION_DEFECT_RATE_4) {
		PRODUCTION_DEFECT_RATE_4 = pRODUCTION_DEFECT_RATE_4;
	}
	public String getPRODUCTION_DEFECT_RATE_5() {
		return PRODUCTION_DEFECT_RATE_5;
	}
	public void setPRODUCTION_DEFECT_RATE_5(String pRODUCTION_DEFECT_RATE_5) {
		PRODUCTION_DEFECT_RATE_5 = pRODUCTION_DEFECT_RATE_5;
	}
	public String getPRODUCTION_DEFECT_RATE_6() {
		return PRODUCTION_DEFECT_RATE_6;
	}
	public void setPRODUCTION_DEFECT_RATE_6(String pRODUCTION_DEFECT_RATE_6) {
		PRODUCTION_DEFECT_RATE_6 = pRODUCTION_DEFECT_RATE_6;
	}
	public String getPRODUCTION_DEFECT_RATE_7() {
		return PRODUCTION_DEFECT_RATE_7;
	}
	public void setPRODUCTION_DEFECT_RATE_7(String pRODUCTION_DEFECT_RATE_7) {
		PRODUCTION_DEFECT_RATE_7 = pRODUCTION_DEFECT_RATE_7;
	}
	public String getPRODUCTION_DEFECT_RATE_8() {
		return PRODUCTION_DEFECT_RATE_8;
	}
	public void setPRODUCTION_DEFECT_RATE_8(String pRODUCTION_DEFECT_RATE_8) {
		PRODUCTION_DEFECT_RATE_8 = pRODUCTION_DEFECT_RATE_8;
	}
	public String getPRODUCTION_DEFECT_RATE_9() {
		return PRODUCTION_DEFECT_RATE_9;
	}
	public void setPRODUCTION_DEFECT_RATE_9(String pRODUCTION_DEFECT_RATE_9) {
		PRODUCTION_DEFECT_RATE_9 = pRODUCTION_DEFECT_RATE_9;
	}
	public String getPRODUCTION_DEFECT_RATE_10() {
		return PRODUCTION_DEFECT_RATE_10;
	}
	public void setPRODUCTION_DEFECT_RATE_10(String pRODUCTION_DEFECT_RATE_10) {
		PRODUCTION_DEFECT_RATE_10 = pRODUCTION_DEFECT_RATE_10;
	}
	public String getPRODUCTION_DEFECT_RATE_11() {
		return PRODUCTION_DEFECT_RATE_11;
	}
	public void setPRODUCTION_DEFECT_RATE_11(String pRODUCTION_DEFECT_RATE_11) {
		PRODUCTION_DEFECT_RATE_11 = pRODUCTION_DEFECT_RATE_11;
	}
	public String getPRODUCTION_DEFECT_RATE_12() {
		return PRODUCTION_DEFECT_RATE_12;
	}
	public void setPRODUCTION_DEFECT_RATE_12(String pRODUCTION_DEFECT_RATE_12) {
		PRODUCTION_DEFECT_RATE_12 = pRODUCTION_DEFECT_RATE_12;
	}
	public String getPRODUCTION_PRODUCT_CODE() {
		return PRODUCTION_PRODUCT_CODE;
	}
	public void setPRODUCTION_PRODUCT_CODE(String pRODUCTION_PRODUCT_CODE) {
		PRODUCTION_PRODUCT_CODE = pRODUCTION_PRODUCT_CODE;
	}
	public String getPRODUCT_ITEM_NAME() {
		return PRODUCT_ITEM_NAME;
	}
	public void setPRODUCT_ITEM_NAME(String pRODUCT_ITEM_NAME) {
		PRODUCT_ITEM_NAME = pRODUCT_ITEM_NAME;
	}
	public String getPRODUCTION_MODIFY_D() {
		return PRODUCTION_MODIFY_D;
	}
	public void setPRODUCTION_MODIFY_D(String pRODUCTION_MODIFY_D) {
		PRODUCTION_MODIFY_D = pRODUCTION_MODIFY_D;
	}
	public String getM() {
		return M;
	}
	public void setM(String m) {
		M = m;
	}
	
	public int getSUM_PRODUCTION_P_Qty() {
		return SUM_PRODUCTION_P_Qty;
	}
	public void setSUM_PRODUCTION_P_Qty(int sUM_PRODUCTION_P_Qty) {
		SUM_PRODUCTION_P_Qty = sUM_PRODUCTION_P_Qty;
	}
	public int getSUM_PRODUCTION_B_Qty() {
		return SUM_PRODUCTION_B_Qty;
	}
	public void setSUM_PRODUCTION_B_Qty(int sUM_PRODUCTION_B_Qty) {
		SUM_PRODUCTION_B_Qty = sUM_PRODUCTION_B_Qty;
	}
	public int getSUM_PRODUCTION_PRODUCTS_VOLUME() {
		return SUM_PRODUCTION_PRODUCTS_VOLUME;
	}
	public void setSUM_PRODUCTION_PRODUCTS_VOLUME(int sUM_PRODUCTION_PRODUCTS_VOLUME) {
		SUM_PRODUCTION_PRODUCTS_VOLUME = sUM_PRODUCTION_PRODUCTS_VOLUME;
	}
	public String getSUM_PRODUCTION_PRODUCTION_DEFECT_RATE() {
		return SUM_PRODUCTION_PRODUCTION_DEFECT_RATE;
	}
	public void setSUM_PRODUCTION_PRODUCTION_DEFECT_RATE(String sUM_PRODUCTION_PRODUCTION_DEFECT_RATE) {
		SUM_PRODUCTION_PRODUCTION_DEFECT_RATE = sUM_PRODUCTION_PRODUCTION_DEFECT_RATE;
	}
	
	
	
	@Override
	public String toString() {
		return "PRODUCTION_INFO_YEAR [Id=" + Id + ", PRODUCTION_P_Qty=" + PRODUCTION_P_Qty + ", PRODUCTION_P_Qty_1="
				+ PRODUCTION_P_Qty_1 + ", PRODUCTION_P_Qty_2=" + PRODUCTION_P_Qty_2 + ", PRODUCTION_P_Qty_3="
				+ PRODUCTION_P_Qty_3 + ", PRODUCTION_P_Qty_4=" + PRODUCTION_P_Qty_4 + ", PRODUCTION_P_Qty_5="
				+ PRODUCTION_P_Qty_5 + ", PRODUCTION_P_Qty_6=" + PRODUCTION_P_Qty_6 + ", PRODUCTION_P_Qty_7="
				+ PRODUCTION_P_Qty_7 + ", PRODUCTION_P_Qty_8=" + PRODUCTION_P_Qty_8 + ", PRODUCTION_P_Qty_9="
				+ PRODUCTION_P_Qty_9 + ", PRODUCTION_P_Qty_10=" + PRODUCTION_P_Qty_10 + ", PRODUCTION_P_Qty_11="
				+ PRODUCTION_P_Qty_11 + ", PRODUCTION_P_Qty_12=" + PRODUCTION_P_Qty_12 + ", PRODUCTION_B_Qty_1="
				+ PRODUCTION_B_Qty_1 + ", PRODUCTION_B_Qty_2=" + PRODUCTION_B_Qty_2 + ", PRODUCTION_B_Qty_3="
				+ PRODUCTION_B_Qty_3 + ", PRODUCTION_B_Qty_4=" + PRODUCTION_B_Qty_4 + ", PRODUCTION_B_Qty_5="
				+ PRODUCTION_B_Qty_5 + ", PRODUCTION_B_Qty_6=" + PRODUCTION_B_Qty_6 + ", PRODUCTION_B_Qty_7="
				+ PRODUCTION_B_Qty_7 + ", PRODUCTION_B_Qty_8=" + PRODUCTION_B_Qty_8 + ", PRODUCTION_B_Qty_9="
				+ PRODUCTION_B_Qty_9 + ", PRODUCTION_B_Qty_10=" + PRODUCTION_B_Qty_10 + ", PRODUCTION_B_Qty_11="
				+ PRODUCTION_B_Qty_11 + ", PRODUCTION_B_Qty_12=" + PRODUCTION_B_Qty_12
				+ ", PRODUCTION_PRODUCTS_VOLUME_1=" + PRODUCTION_PRODUCTS_VOLUME_1 + ", PRODUCTION_PRODUCTS_VOLUME_2="
				+ PRODUCTION_PRODUCTS_VOLUME_2 + ", PRODUCTION_PRODUCTS_VOLUME_3=" + PRODUCTION_PRODUCTS_VOLUME_3
				+ ", PRODUCTION_PRODUCTS_VOLUME_4=" + PRODUCTION_PRODUCTS_VOLUME_4 + ", PRODUCTION_PRODUCTS_VOLUME_5="
				+ PRODUCTION_PRODUCTS_VOLUME_5 + ", PRODUCTION_PRODUCTS_VOLUME_6=" + PRODUCTION_PRODUCTS_VOLUME_6
				+ ", PRODUCTION_PRODUCTS_VOLUME_7=" + PRODUCTION_PRODUCTS_VOLUME_7 + ", PRODUCTION_PRODUCTS_VOLUME_8="
				+ PRODUCTION_PRODUCTS_VOLUME_8 + ", PRODUCTION_PRODUCTS_VOLUME_9=" + PRODUCTION_PRODUCTS_VOLUME_9
				+ ", PRODUCTION_PRODUCTS_VOLUME_10=" + PRODUCTION_PRODUCTS_VOLUME_10
				+ ", PRODUCTION_PRODUCTS_VOLUME_11=" + PRODUCTION_PRODUCTS_VOLUME_11
				+ ", PRODUCTION_PRODUCTS_VOLUME_12=" + PRODUCTION_PRODUCTS_VOLUME_12 + ", PRODUCTION_DEFECT_RATE_1="
				+ PRODUCTION_DEFECT_RATE_1 + ", PRODUCTION_DEFECT_RATE_2=" + PRODUCTION_DEFECT_RATE_2
				+ ", PRODUCTION_DEFECT_RATE_3=" + PRODUCTION_DEFECT_RATE_3 + ", PRODUCTION_DEFECT_RATE_4="
				+ PRODUCTION_DEFECT_RATE_4 + ", PRODUCTION_DEFECT_RATE_5=" + PRODUCTION_DEFECT_RATE_5
				+ ", PRODUCTION_DEFECT_RATE_6=" + PRODUCTION_DEFECT_RATE_6 + ", PRODUCTION_DEFECT_RATE_7="
				+ PRODUCTION_DEFECT_RATE_7 + ", PRODUCTION_DEFECT_RATE_8=" + PRODUCTION_DEFECT_RATE_8
				+ ", PRODUCTION_DEFECT_RATE_9=" + PRODUCTION_DEFECT_RATE_9 + ", PRODUCTION_DEFECT_RATE_10="
				+ PRODUCTION_DEFECT_RATE_10 + ", PRODUCTION_DEFECT_RATE_11=" + PRODUCTION_DEFECT_RATE_11
				+ ", PRODUCTION_DEFECT_RATE_12=" + PRODUCTION_DEFECT_RATE_12 + ", PRODUCTION_PRODUCT_CODE="
				+ PRODUCTION_PRODUCT_CODE + ", PRODUCT_ITEM_NAME=" + PRODUCT_ITEM_NAME + ", PRODUCTION_MODIFY_D="
				+ PRODUCTION_MODIFY_D + ", M=" + M + ", SUM_PRODUCTION_P_Qty=" + SUM_PRODUCTION_P_Qty
				+ ", SUM_PRODUCTION_B_Qty=" + SUM_PRODUCTION_B_Qty + ", SUM_PRODUCTION_PRODUCTS_VOLUME="
				+ SUM_PRODUCTION_PRODUCTS_VOLUME + ", SUM_PRODUCTION_PRODUCTION_DEFECT_RATE="
				+ SUM_PRODUCTION_PRODUCTION_DEFECT_RATE + "]";
	}
	

	
	public PRODUCTION_INFO_YEAR() {
		super();
	}
	
}