package com.Production.Dto;

public class PRODUCTION_INFO_ {

	private int Id;
	private String PRODUCTION_SERIAL_NUM; // 시리얼 넘버
	private String PRODUCTION_INFO_NUM; // 순번
	private String PRODUCTION_EQUIPMENT_CODE; // 설비코드
	private String PRODUCTION_EQUIPMENT_INFO_NAME; // 설비명
	private int PRODUCTION_P_Qty; // 생산수량
	private String PRODUCTION_DEFECT_CODE; // 불량정보No
	private String PRODUCTION_DEFECT_NAME; // 불량명
	private int PRODUCTION_B_Qty; // 불량수량
	private int PRODUCTION_PRODUCTS_VOLUM; // 양품수량
	private int PRODUCTION_PRODUCTS_VOLUME; // 양품수량
	private String PRODUCTION_DEFECT_RATE; // 불량율
	private String PRODUCTION_PRODUCT_CODE; // 제품No
	private String PRODUCT_ITEM_NAME; // 제품명
	private String PRODUCTION_MOLD_INFO_CODE;// 금형코드
	private String PRODUCTION_MOLD_INFO_NAME;// 금형명
	private String PRODUCTION_USER_NAME; // 사용자명
	private String PRODUCTION_USER_CODE; // 사용자코드
	private String PRODUCTION_MODIFY_D; // 날짜
	private String M; // 월
	private String PRODUCTION_CC; // 구분
	
	public int getId() {
		return Id;
	}
	public void setId(int id) {
		Id = id;
	}
	public String getM() {
		return M;
	}
	public void setM(String m) {
		M = m;
	}
	public String getPRODUCTION_SERIAL_NUM() {
		return PRODUCTION_SERIAL_NUM;
	}
	public void setPRODUCTION_SERIAL_NUM(String pRODUCTION_SERIAL_NUM) {
		PRODUCTION_SERIAL_NUM = pRODUCTION_SERIAL_NUM;
	}
	public String getPRODUCTION_INFO_NUM() {
		return PRODUCTION_INFO_NUM;
	}
	public void setPRODUCTION_INFO_NUM(String pRODUCTION_INFO_NUM) {
		PRODUCTION_INFO_NUM = pRODUCTION_INFO_NUM;
	}
	public String getPRODUCTION_EQUIPMENT_CODE() {
		return PRODUCTION_EQUIPMENT_CODE;
	}
	public void setPRODUCTION_EQUIPMENT_CODE(String pRODUCTION_EQUIPMENT_CODE) {
		PRODUCTION_EQUIPMENT_CODE = pRODUCTION_EQUIPMENT_CODE;
	}
	public String getPRODUCTION_EQUIPMENT_INFO_NAME() {
		return PRODUCTION_EQUIPMENT_INFO_NAME;
	}
	public void setPRODUCTION_EQUIPMENT_INFO_NAME(String pRODUCTION_EQUIPMENT_INFO_NAME) {
		PRODUCTION_EQUIPMENT_INFO_NAME = pRODUCTION_EQUIPMENT_INFO_NAME;
	}
	public int getPRODUCTION_P_Qty() {
		return PRODUCTION_P_Qty;
	}
	public void setPRODUCTION_P_Qty(int pRODUCTION_P_Qty) {
		PRODUCTION_P_Qty = pRODUCTION_P_Qty;
	}
	public String getPRODUCTION_DEFECT_CODE() {
		return PRODUCTION_DEFECT_CODE;
	}
	public void setPRODUCTION_DEFECT_CODE(String pRODUCTION_DEFECT_CODE) {
		PRODUCTION_DEFECT_CODE = pRODUCTION_DEFECT_CODE;
	}
	public String getPRODUCTION_DEFECT_NAME() {
		return PRODUCTION_DEFECT_NAME;
	}
	public void setPRODUCTION_DEFECT_NAME(String pRODUCTION_DEFECT_NAME) {
		PRODUCTION_DEFECT_NAME = pRODUCTION_DEFECT_NAME;
	}
	public int getPRODUCTION_B_Qty() {
		return PRODUCTION_B_Qty;
	}
	public void setPRODUCTION_B_Qty(int pRODUCTION_B_Qty) {
		PRODUCTION_B_Qty = pRODUCTION_B_Qty;
	}
	public int getPRODUCTION_PRODUCTS_VOLUM() {
		return PRODUCTION_PRODUCTS_VOLUM;
	}
	public void setPRODUCTION_PRODUCTS_VOLUM(int pRODUCTION_PRODUCTS_VOLUM) {
		PRODUCTION_PRODUCTS_VOLUM = pRODUCTION_PRODUCTS_VOLUM;
	}
	public int getPRODUCTION_PRODUCTS_VOLUME() {
		return PRODUCTION_PRODUCTS_VOLUME;
	}
	public void setPRODUCTION_PRODUCTS_VOLUME(int pRODUCTION_PRODUCTS_VOLUME) {
		PRODUCTION_PRODUCTS_VOLUME = pRODUCTION_PRODUCTS_VOLUME;
	}
	public String getPRODUCTION_DEFECT_RATE() {
		return PRODUCTION_DEFECT_RATE;
	}
	public void setPRODUCTION_DEFECT_RATE(String pRODUCTION_DEFECT_RATE) {
		PRODUCTION_DEFECT_RATE = pRODUCTION_DEFECT_RATE;
	}
	public String getPRODUCTION_PRODUCT_CODE() {
		return PRODUCTION_PRODUCT_CODE;
	}
	public void setPRODUCTION_PRODUCT_CODE(String pRODUCTION_PRODUCT_CODE) {
		PRODUCTION_PRODUCT_CODE = pRODUCTION_PRODUCT_CODE;
	}
	public String getPRODUCT_ITEM_NAME() {
		return PRODUCT_ITEM_NAME;
	}
	public void setPRODUCT_ITEM_NAME(String pRODUCT_ITEM_NAME) {
		PRODUCT_ITEM_NAME = pRODUCT_ITEM_NAME;
	}
	public String getPRODUCTION_MOLD_INFO_CODE() {
		return PRODUCTION_MOLD_INFO_CODE;
	}
	public void setPRODUCTION_MOLD_INFO_CODE(String pRODUCTION_MOLD_INFO_CODE) {
		PRODUCTION_MOLD_INFO_CODE = pRODUCTION_MOLD_INFO_CODE;
	}
	public String getPRODUCTION_MOLD_INFO_NAME() {
		return PRODUCTION_MOLD_INFO_NAME;
	}
	public void setPRODUCTION_MOLD_INFO_NAME(String pRODUCTION_MOLD_INFO_NAME) {
		PRODUCTION_MOLD_INFO_NAME = pRODUCTION_MOLD_INFO_NAME;
	}
	public String getPRODUCTION_USER_NAME() {
		return PRODUCTION_USER_NAME;
	}
	public void setPRODUCTION_USER_NAME(String pRODUCTION_USER_NAME) {
		PRODUCTION_USER_NAME = pRODUCTION_USER_NAME;
	}
	public String getPRODUCTION_USER_CODE() {
		return PRODUCTION_USER_CODE;
	}
	public void setPRODUCTION_USER_CODE(String pRODUCTION_USER_CODE) {
		PRODUCTION_USER_CODE = pRODUCTION_USER_CODE;
	}
	public String getPRODUCTION_MODIFY_D() {
		return PRODUCTION_MODIFY_D;
	}
	public void setPRODUCTION_MODIFY_D(String pRODUCTION_MODIFY_D) {
		PRODUCTION_MODIFY_D = pRODUCTION_MODIFY_D;
	}
	public String getPRODUCTION_CC() {
		return PRODUCTION_CC;
	}
	public void setPRODUCTION_CC(String pRODUCTION_CC) {
		PRODUCTION_CC = pRODUCTION_CC;
	}
	public PRODUCTION_INFO_() {
		super();
	}
	@Override
	public String toString() {
		return "PRODUCTION_INFO_ [Id=" + Id + ", PRODUCTION_SERIAL_NUM=" + PRODUCTION_SERIAL_NUM
				+ ", PRODUCTION_INFO_NUM=" + PRODUCTION_INFO_NUM + ", PRODUCTION_EQUIPMENT_CODE="
				+ PRODUCTION_EQUIPMENT_CODE + ", PRODUCTION_EQUIPMENT_INFO_NAME=" + PRODUCTION_EQUIPMENT_INFO_NAME
				+ ", PRODUCTION_P_Qty=" + PRODUCTION_P_Qty + ", PRODUCTION_DEFECT_CODE=" + PRODUCTION_DEFECT_CODE
				+ ", PRODUCTION_DEFECT_NAME=" + PRODUCTION_DEFECT_NAME + ", PRODUCTION_B_Qty=" + PRODUCTION_B_Qty
				+ ", PRODUCTION_PRODUCTS_VOLUM=" + PRODUCTION_PRODUCTS_VOLUM + ", PRODUCTION_PRODUCTS_VOLUME="
				+ PRODUCTION_PRODUCTS_VOLUME + ", PRODUCTION_DEFECT_RATE=" + PRODUCTION_DEFECT_RATE
				+ ", PRODUCTION_PRODUCT_CODE=" + PRODUCTION_PRODUCT_CODE + ", PRODUCT_ITEM_NAME=" + PRODUCT_ITEM_NAME
				+ ", PRODUCTION_MOLD_INFO_CODE=" + PRODUCTION_MOLD_INFO_CODE + ", PRODUCTION_MOLD_INFO_NAME="
				+ PRODUCTION_MOLD_INFO_NAME + ", PRODUCTION_USER_NAME=" + PRODUCTION_USER_NAME
				+ ", PRODUCTION_USER_CODE=" + PRODUCTION_USER_CODE + ", PRODUCTION_MODIFY_D=" + PRODUCTION_MODIFY_D
				+ ", M=" + M + ", PRODUCTION_CC=" + PRODUCTION_CC + "]";
	}
	public PRODUCTION_INFO_(int id, String pRODUCTION_SERIAL_NUM, String pRODUCTION_INFO_NUM,
			String pRODUCTION_EQUIPMENT_CODE, String pRODUCTION_EQUIPMENT_INFO_NAME, int pRODUCTION_P_Qty,
			String pRODUCTION_DEFECT_CODE, String pRODUCTION_DEFECT_NAME, int pRODUCTION_B_Qty,
			int pRODUCTION_PRODUCTS_VOLUM, int pRODUCTION_PRODUCTS_VOLUME, String pRODUCTION_DEFECT_RATE,
			String pRODUCTION_PRODUCT_CODE, String pRODUCT_ITEM_NAME, String pRODUCTION_MOLD_INFO_CODE,
			String pRODUCTION_MOLD_INFO_NAME, String pRODUCTION_USER_NAME, String pRODUCTION_USER_CODE,
			String pRODUCTION_MODIFY_D, String m, String pRODUCTION_CC) {
		super();
		Id = id;
		PRODUCTION_SERIAL_NUM = pRODUCTION_SERIAL_NUM;
		PRODUCTION_INFO_NUM = pRODUCTION_INFO_NUM;
		PRODUCTION_EQUIPMENT_CODE = pRODUCTION_EQUIPMENT_CODE;
		PRODUCTION_EQUIPMENT_INFO_NAME = pRODUCTION_EQUIPMENT_INFO_NAME;
		PRODUCTION_P_Qty = pRODUCTION_P_Qty;
		PRODUCTION_DEFECT_CODE = pRODUCTION_DEFECT_CODE;
		PRODUCTION_DEFECT_NAME = pRODUCTION_DEFECT_NAME;
		PRODUCTION_B_Qty = pRODUCTION_B_Qty;
		PRODUCTION_PRODUCTS_VOLUM = pRODUCTION_PRODUCTS_VOLUM;
		PRODUCTION_PRODUCTS_VOLUME = pRODUCTION_PRODUCTS_VOLUME;
		PRODUCTION_DEFECT_RATE = pRODUCTION_DEFECT_RATE;
		PRODUCTION_PRODUCT_CODE = pRODUCTION_PRODUCT_CODE;
		PRODUCT_ITEM_NAME = pRODUCT_ITEM_NAME;
		PRODUCTION_MOLD_INFO_CODE = pRODUCTION_MOLD_INFO_CODE;
		PRODUCTION_MOLD_INFO_NAME = pRODUCTION_MOLD_INFO_NAME;
		PRODUCTION_USER_NAME = pRODUCTION_USER_NAME;
		PRODUCTION_USER_CODE = pRODUCTION_USER_CODE;
		PRODUCTION_MODIFY_D = pRODUCTION_MODIFY_D;
		M = m;
		PRODUCTION_CC = pRODUCTION_CC;
	}
	
	
	
}