package com.Standard.Dto;

public class EQUIPMENT_INFO_TBL {

	private int id;
	private String EQUIPMENT_BUSINESS_PLACE; // 사업장(세부테이블)
	private String EQUIPMENT_BUSINESS_PLACE_NAME; // 사업장명(조인)
	private String EQUIPMENT_INFO_CODE; // 설비코드(기본키)
	private String EQUIPMENT_INFO_NAME; // 설비명
	private String EQUIPMENT_INFO_ABR; // 설비호기
	private float EQUIPMENT_HEIGHT; // 설비(높이)
	private float EQUIPMENT_WIDTH; // 설비(폭)
	private float EQUIPMENT_DEPTH; // 설비(깊이)
	private String EQUIPMENT_SERIAL_NUM; // 설비(시리얼 넘버)
	private float EQUIPMENT_WEIGHT; // 설비(무게)
	private String EQUIPMENT_RECEIVED_D; // 설비 구입일자
	private String EQUIPMENT_MODEL_YEAR; // 설비 연식
	private String EQUIPMENT_MANUFACTURER; // 제작압체
	private String EQUIPMENT_STATUS; // 설비상태(세부코드)
	private String EQUIPMENT_STATUS_NAME; // 설비상태명(조인)
	private String EQUIPMENT_INFO_RMARK; // 비고
	private String EQUIPMENT_USE_STATUS; // 사용유무
	private String EQUIPMENT_MODIFY_D; // 수정일자
	private String EQUIPMENT_MODIFIER; // 수정자
	private String EQUIPMENT_FilePath; // 설비 사진

	public EQUIPMENT_INFO_TBL(String eQUIPMENT_BUSINESS_PLACE, String eQUIPMENT_BUSINESS_PLACE_NAME,
			String eQUIPMENT_INFO_CODE, String eQUIPMENT_INFO_NAME, String eQUIPMENT_INFO_ABR, float eQUIPMENT_HEIGHT,
			float eQUIPMENT_WIDTH, float eQUIPMENT_DEPTH, String eQUIPMENT_SERIAL_NUM, float eQUIPMENT_WEIGHT,
			String eQUIPMENT_RECEIVED_D, String eQUIPMENT_MODEL_YEAR, String eQUIPMENT_MANUFACTURER,
			String eQUIPMENT_STATUS, String eQUIPMENT_STATUS_NAME, String eQUIPMENT_INFO_RMARK,
			String eQUIPMENT_USE_STATUS, String eQUIPMENT_MODIFY_D, String eQUIPMENT_MODIFIER,
			String eQUIPMENT_FilePath) {
		super();
		EQUIPMENT_BUSINESS_PLACE = eQUIPMENT_BUSINESS_PLACE;
		EQUIPMENT_BUSINESS_PLACE_NAME = eQUIPMENT_BUSINESS_PLACE_NAME;
		EQUIPMENT_INFO_CODE = eQUIPMENT_INFO_CODE;
		EQUIPMENT_INFO_NAME = eQUIPMENT_INFO_NAME;
		EQUIPMENT_INFO_ABR = eQUIPMENT_INFO_ABR;
		EQUIPMENT_HEIGHT = eQUIPMENT_HEIGHT;
		EQUIPMENT_WIDTH = eQUIPMENT_WIDTH;
		EQUIPMENT_DEPTH = eQUIPMENT_DEPTH;
		EQUIPMENT_SERIAL_NUM = eQUIPMENT_SERIAL_NUM;
		EQUIPMENT_WEIGHT = eQUIPMENT_WEIGHT;
		EQUIPMENT_RECEIVED_D = eQUIPMENT_RECEIVED_D;
		EQUIPMENT_MODEL_YEAR = eQUIPMENT_MODEL_YEAR;
		EQUIPMENT_MANUFACTURER = eQUIPMENT_MANUFACTURER;
		EQUIPMENT_STATUS = eQUIPMENT_STATUS;
		EQUIPMENT_STATUS_NAME = eQUIPMENT_STATUS_NAME;
		EQUIPMENT_INFO_RMARK = eQUIPMENT_INFO_RMARK;
		EQUIPMENT_USE_STATUS = eQUIPMENT_USE_STATUS;
		EQUIPMENT_MODIFY_D = eQUIPMENT_MODIFY_D;
		EQUIPMENT_MODIFIER = eQUIPMENT_MODIFIER;
		EQUIPMENT_FilePath = eQUIPMENT_FilePath;
	}

	public EQUIPMENT_INFO_TBL() {
		super();
	}

	@Override
	public String toString() {
		return "EQUIPMENT_INFO_TBL [EQUIPMENT_BUSINESS_PLACE=" + EQUIPMENT_BUSINESS_PLACE
				+ ", EQUIPMENT_BUSINESS_PLACE_NAME=" + EQUIPMENT_BUSINESS_PLACE_NAME + ", EQUIPMENT_INFO_CODE="
				+ EQUIPMENT_INFO_CODE + ", EQUIPMENT_INFO_NAME=" + EQUIPMENT_INFO_NAME + ", EQUIPMENT_INFO_ABR="
				+ EQUIPMENT_INFO_ABR + ", EQUIPMENT_HEIGHT=" + EQUIPMENT_HEIGHT + ", EQUIPMENT_WIDTH=" + EQUIPMENT_WIDTH
				+ ", EQUIPMENT_DEPTH=" + EQUIPMENT_DEPTH + ", EQUIPMENT_SERIAL_NUM=" + EQUIPMENT_SERIAL_NUM
				+ ", EQUIPMENT_WEIGHT=" + EQUIPMENT_WEIGHT + ", EQUIPMENT_RECEIVED_D=" + EQUIPMENT_RECEIVED_D
				+ ", EQUIPMENT_MODEL_YEAR=" + EQUIPMENT_MODEL_YEAR + ", EQUIPMENT_MANUFACTURER="
				+ EQUIPMENT_MANUFACTURER + ", EQUIPMENT_STATUS=" + EQUIPMENT_STATUS + ", EQUIPMENT_STATUS_NAME="
				+ EQUIPMENT_STATUS_NAME + ", EQUIPMENT_INFO_RMARK=" + EQUIPMENT_INFO_RMARK + ", EQUIPMENT_USE_STATUS="
				+ EQUIPMENT_USE_STATUS + ", EQUIPMENT_MODIFY_D=" + EQUIPMENT_MODIFY_D + ", EQUIPMENT_MODIFIER="
				+ EQUIPMENT_MODIFIER + ", EQUIPMENT_FilePath=" + EQUIPMENT_FilePath + ", getEQUIPMENT_BUSINESS_PLACE()="
				+ getEQUIPMENT_BUSINESS_PLACE() + ", getEQUIPMENT_BUSINESS_PLACE_NAME()="
				+ getEQUIPMENT_BUSINESS_PLACE_NAME() + ", getEQUIPMENT_INFO_CODE()=" + getEQUIPMENT_INFO_CODE()
				+ ", getEQUIPMENT_INFO_NAME()=" + getEQUIPMENT_INFO_NAME() + ", getEQUIPMENT_INFO_ABR()="
				+ getEQUIPMENT_INFO_ABR() + ", getEQUIPMENT_HEIGHT()=" + getEQUIPMENT_HEIGHT()
				+ ", getEQUIPMENT_WIDTH()=" + getEQUIPMENT_WIDTH() + ", getEQUIPMENT_DEPTH()=" + getEQUIPMENT_DEPTH()
				+ ", getEQUIPMENT_SERIAL_NUM()=" + getEQUIPMENT_SERIAL_NUM() + ", getEQUIPMENT_WEIGHT()="
				+ getEQUIPMENT_WEIGHT() + ", getEQUIPMENT_RECEIVED_D()=" + getEQUIPMENT_RECEIVED_D()
				+ ", getEQUIPMENT_MODEL_YEAR()=" + getEQUIPMENT_MODEL_YEAR() + ", getEQUIPMENT_MANUFACTURER()="
				+ getEQUIPMENT_MANUFACTURER() + ", getEQUIPMENT_STATUS()=" + getEQUIPMENT_STATUS()
				+ ", getEQUIPMENT_STATUS_NAME()=" + getEQUIPMENT_STATUS_NAME() + ", getEQUIPMENT_INFO_RMARK()="
				+ getEQUIPMENT_INFO_RMARK() + ", getEQUIPMENT_USE_STATUS()=" + getEQUIPMENT_USE_STATUS()
				+ ", getEQUIPMENT_MODIFY_D()=" + getEQUIPMENT_MODIFY_D() + ", getEQUIPMENT_MODIFIER()="
				+ getEQUIPMENT_MODIFIER() + ", getEQUIPMENT_FilePath()=" + getEQUIPMENT_FilePath() + ", getClass()="
				+ getClass() + ", hashCode()=" + hashCode() + ", toString()=" + super.toString() + "]";
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getEQUIPMENT_BUSINESS_PLACE() {
		return EQUIPMENT_BUSINESS_PLACE;
	}

	public void setEQUIPMENT_BUSINESS_PLACE(String eQUIPMENT_BUSINESS_PLACE) {
		EQUIPMENT_BUSINESS_PLACE = eQUIPMENT_BUSINESS_PLACE;
	}

	public String getEQUIPMENT_BUSINESS_PLACE_NAME() {
		return EQUIPMENT_BUSINESS_PLACE_NAME;
	}

	public void setEQUIPMENT_BUSINESS_PLACE_NAME(String eQUIPMENT_BUSINESS_PLACE_NAME) {
		EQUIPMENT_BUSINESS_PLACE_NAME = eQUIPMENT_BUSINESS_PLACE_NAME;
	}

	public String getEQUIPMENT_INFO_CODE() {
		return EQUIPMENT_INFO_CODE;
	}

	public void setEQUIPMENT_INFO_CODE(String eQUIPMENT_INFO_CODE) {
		EQUIPMENT_INFO_CODE = eQUIPMENT_INFO_CODE;
	}

	public String getEQUIPMENT_INFO_NAME() {
		return EQUIPMENT_INFO_NAME;
	}

	public void setEQUIPMENT_INFO_NAME(String eQUIPMENT_INFO_NAME) {
		EQUIPMENT_INFO_NAME = eQUIPMENT_INFO_NAME;
	}

	public String getEQUIPMENT_INFO_ABR() {
		return EQUIPMENT_INFO_ABR;
	}

	public void setEQUIPMENT_INFO_ABR(String eQUIPMENT_INFO_ABR) {
		EQUIPMENT_INFO_ABR = eQUIPMENT_INFO_ABR;
	}

	public float getEQUIPMENT_HEIGHT() {
		return EQUIPMENT_HEIGHT;
	}

	public void setEQUIPMENT_HEIGHT(float eQUIPMENT_HEIGHT) {
		EQUIPMENT_HEIGHT = eQUIPMENT_HEIGHT;
	}

	public float getEQUIPMENT_WIDTH() {
		return EQUIPMENT_WIDTH;
	}

	public void setEQUIPMENT_WIDTH(float eQUIPMENT_WIDTH) {
		EQUIPMENT_WIDTH = eQUIPMENT_WIDTH;
	}

	public float getEQUIPMENT_DEPTH() {
		return EQUIPMENT_DEPTH;
	}

	public void setEQUIPMENT_DEPTH(float eQUIPMENT_DEPTH) {
		EQUIPMENT_DEPTH = eQUIPMENT_DEPTH;
	}

	public String getEQUIPMENT_SERIAL_NUM() {
		return EQUIPMENT_SERIAL_NUM;
	}

	public void setEQUIPMENT_SERIAL_NUM(String eQUIPMENT_SERIAL_NUM) {
		EQUIPMENT_SERIAL_NUM = eQUIPMENT_SERIAL_NUM;
	}

	public float getEQUIPMENT_WEIGHT() {
		return EQUIPMENT_WEIGHT;
	}

	public void setEQUIPMENT_WEIGHT(float eQUIPMENT_WEIGHT) {
		EQUIPMENT_WEIGHT = eQUIPMENT_WEIGHT;
	}

	public String getEQUIPMENT_RECEIVED_D() {
		return EQUIPMENT_RECEIVED_D;
	}

	public void setEQUIPMENT_RECEIVED_D(String eQUIPMENT_RECEIVED_D) {
		EQUIPMENT_RECEIVED_D = eQUIPMENT_RECEIVED_D;
	}

	public String getEQUIPMENT_MODEL_YEAR() {
		return EQUIPMENT_MODEL_YEAR;
	}

	public void setEQUIPMENT_MODEL_YEAR(String eQUIPMENT_MODEL_YEAR) {
		EQUIPMENT_MODEL_YEAR = eQUIPMENT_MODEL_YEAR;
	}

	public String getEQUIPMENT_MANUFACTURER() {
		return EQUIPMENT_MANUFACTURER;
	}

	public void setEQUIPMENT_MANUFACTURER(String eQUIPMENT_MANUFACTURER) {
		EQUIPMENT_MANUFACTURER = eQUIPMENT_MANUFACTURER;
	}

	public String getEQUIPMENT_STATUS() {
		return EQUIPMENT_STATUS;
	}

	public void setEQUIPMENT_STATUS(String eQUIPMENT_STATUS) {
		EQUIPMENT_STATUS = eQUIPMENT_STATUS;
	}

	public String getEQUIPMENT_STATUS_NAME() {
		return EQUIPMENT_STATUS_NAME;
	}

	public void setEQUIPMENT_STATUS_NAME(String eQUIPMENT_STATUS_NAME) {
		EQUIPMENT_STATUS_NAME = eQUIPMENT_STATUS_NAME;
	}

	public String getEQUIPMENT_INFO_RMARK() {
		return EQUIPMENT_INFO_RMARK;
	}

	public void setEQUIPMENT_INFO_RMARK(String eQUIPMENT_INFO_RMARK) {
		EQUIPMENT_INFO_RMARK = eQUIPMENT_INFO_RMARK;
	}

	public String getEQUIPMENT_USE_STATUS() {
		return EQUIPMENT_USE_STATUS;
	}

	public void setEQUIPMENT_USE_STATUS(String eQUIPMENT_USE_STATUS) {
		EQUIPMENT_USE_STATUS = eQUIPMENT_USE_STATUS;
	}

	public String getEQUIPMENT_MODIFY_D() {
		return EQUIPMENT_MODIFY_D;
	}

	public void setEQUIPMENT_MODIFY_D(String eQUIPMENT_MODIFY_D) {
		EQUIPMENT_MODIFY_D = eQUIPMENT_MODIFY_D;
	}

	public String getEQUIPMENT_MODIFIER() {
		return EQUIPMENT_MODIFIER;
	}

	public void setEQUIPMENT_MODIFIER(String eQUIPMENT_MODIFIER) {
		EQUIPMENT_MODIFIER = eQUIPMENT_MODIFIER;
	}

	public String getEQUIPMENT_FilePath() {
		return EQUIPMENT_FilePath;
	}

	public void setEQUIPMENT_FilePath(String eQUIPMENT_FilePath) {
		EQUIPMENT_FilePath = eQUIPMENT_FilePath;
	}

}
